name: Build and Push Docker Image

on:
  push:
    branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub 
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER_AGAIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN_AGAIN }}

      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ vars.DOCKERHUB_USER_AGAIN }}/github-actions-app:latest
            ${{ vars.DOCKERHUB_USER_AGAIN }}/github-actions-app:${{ env.SHORT_SHA }}
