name: Build and push 

on:
    workflow_dispatch: 

jobs:
    build-and-push:
        runs-on: ubuntu-latest 

        steps:
            - name: checkout code 
              uses: actions/checkout@v4

            - name: Login to Docker hub 
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USER_AGAIN }}
                  password: ${{ secrets.DOCKERHUB_TOKEN_AGAIN }}

            - name: Build & push to Docker hub
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true 
                  tags: |
                      ${{ vars.DOCKERHUB_USER_AGAIN }}/github-actions-app:${{ github.ref_name }}
                      ${{ vars.DOCKERHUB_USER_AGAIN }}/github-actions-app:latest
                      ${{ vars.DOCKERHUB_USER_AGAIN }}/github-actions-app:${{ github.sha }}

                    
