name: Hello

on:
  push:
    branches: [main]
    paths:
      - '**.html'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to frnds
        run: echo "Hello Dosto"

      - name: Say hello to users
        run : echo "Hello Users"
