name: Hello

on:
    workflow_dispatch: 

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v4

      - name: Say hello to github action
        run : echo "Hello from GitHub Actions!"
