name: Manual Trigger

on:
  workflow_dispatch:
    enviorments:
      description: "choose enviorment"
      required: true
      default: "staging"


jobs:
  run-manual:
    runs-on: ubuntu-latest

    steps:
      - name: Print selected environment
        run: echo "Deployment environment is ${{ github.event.inputs.environment }}"

